### PR TITLE
added straight-bot

### PR DESCRIPTION
**Pull request by raks097**

### CODE REVIEW

**Comment by crizCraig** [comment]
:robot: Autogenerated botleague evaluation comment:

Container logs for your evaluation:
*  https://storage.googleapis.com/deepdriveio/deepdrive_botleague_logs/deepdriveio/deepdrive:problem_unprotected_left_job-2020-02-26_10-39-56_GKVND8LZ83BI0HLU9IB65RRG5.txt
* https://storage.googleapis.com/deepdriveio/deepdrive_botleague_logs/rakshith097/deepdrive:test_job-2020-02-26_10-39-56_GKVND8LZ83BI0HLU9IB65RRG5.txt

Full results: https://gist.github.com/a1e14f291648fc74cee2b57a6394390f

**Comment by crizCraig** [comment]
:robot: Autogenerated botleague evaluation comment:

Container logs for your evaluation:
*  https://storage.googleapis.com/deepdriveio/deepdrive_botleague_logs/deepdriveio/deepdrive:problem_unprotected_left_job-2020-02-26_13-13-51_UIGR1239TACCTAHB38WJTYI7P.txt
* https://storage.googleapis.com/deepdriveio/deepdrive_botleague_logs/rakshith097/deepdrive:test_job-2020-02-26_13-13-51_UIGR1239TACCTAHB38WJTYI7P.txt

Full results: https://gist.github.com/f8f4633e991d4a07cbd137744c427bd7

**Comment by crizCraig** [comment]
This `json_mode` error is likely on are side @raks097. I'll look into it.

**Comment by crizCraig** [comment]
This `json_mode` error is likely on are side @raks097. I'll look into it, and sorry about this!

**Comment by raks097** [comment]
> This `json_mode` error is likely on are side @raks097. I'll look into it, and sorry about this!

Sure thing, Thanks.

**Comment by crizCraig** [comment]
:robot: Autogenerated botleague evaluation comment:

Container logs for your evaluation:
*  https://storage.googleapis.com/deepdriveio/deepdrive_botleague_logs/deepdriveio/deepdrive:problem_unprotected_left_job-2020-02-28_04-02-00_TSF0E5QTBLHZJRMWAGTUL52JV.txt
* https://storage.googleapis.com/deepdriveio/deepdrive_botleague_logs/rakshith097/deepdrive:test_job-2020-02-28_04-02-00_TSF0E5QTBLHZJRMWAGTUL52JV.txt

Full results: https://gist.github.com/08d90708110c35a836d4fc72b4341e3c

**Comment by crizCraig** [comment]
:tada:

**Pull request merged**
